spring:
   profiles:
      active:
         - dev
---
spring:
   profiles: dev
   application:
      name: cloudTestConfig-test-dev
---
spring:
   profiles: default
   application:
      name: cloudTestConfig-test-default
