spring:
   profiles:
      active:
         - dev
---
server:
   port: 8301
spring:
   profiles: dev
   application:
      name: cloudTestConfig-config-client

eureka:
   client:
      service-url:
         defaultZone: http://admindev:admindev@eureka-config.com:7301/eureka
---
server:
   port: 8301
spring:
   profiles: beta
   application:
      name: cloudTestConfig-config-client

eureka:
   client:
      service-url:
         defaultZone: http://admindev:admindev@eureka-config.com:7301/eureka