spring:
   profiles:
      active:
         - dev
---
spring:
   profiles: dev
      application:
         name: cloudTest-config-eureka-client
server:
   port: 7001
security:
   basic:
      enable: true
   user:
      name: admindev
      password: admindev
eureka:
   client:
      service-url:
         defaultZone: http://admin:admin@eureka-7001.com:7001/eureka
      register-with-eureka: false
      fetch-registry: false
   instance:
      hostname: eureka-7001.com
      
      
      
---
spring:
   profiles: beta
      application:
         name: cloudTest-config-eureka-client
server:
   port: 7001
security:
   basic:
      enable: true
   user:
      name: adminbeta
      password: adminbeta
eureka:
   client:
      service-url:
         defaultZone: http://admin:admin@eureka-7001.com:7001/eureka
      register-with-eureka: false
      fetch-registry: false
   instance:
      hostname: eureka-7001.com