spring:
   profiles:
      active:
         - dev
---
server:
   port: 8201
spring:
   profiles: dev
   application:
      name: cloudTestConfig-config-client

eureka:
   client:
      service-url:
         defaultZone: http://admin:admin@eureka-dev.com:7001/eureka
---
server:
   port: 8102
spring:
   profiles: beta
   application:
      name: cloudTestConfig-config-client

eureka:
   client:
      service-url:
         defaultZone: http://admin:admin@eureka-beta.com:7001/eureka